import cross_domain_transferable_perturbations.eval as eval
import cross_domain_transferable_perturbations
import cross_domain_transferable_perturbations.eval_test as eval_test
eval.main()
#eval_test.main()