[paths]
save = 'results/'

[training]
batch_size = 150

[model]
name = 'vgg16'
instantiate = "VGG(vgg.make_layers([64, 64, 'M', 128, 128, 'M', 256, 256, 256, 'M', 512, 512, 512, 'M', 512, 512, 512, 'M']), num_classes=NUM_CLASSES)"  # torchvision instantiation
