[paths]
data = '/data/vision/torralba/datasets/places/files'
save = 'results/'

[training]
BATCH_SIZE = 256

[model]
name = 'googlenet'
instantiate = 'GoogLeNet(num_classes=NUM_CLASSES)'  # torchvision instantiation
aux_weights = [0.4, 0.3, 0.3]  # how to weight Auxiliary classifiers